@baseUrl = http://localhost:3333
@AuthToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "raimones",
  "email": "rai@email.com",
  "password": "12345678"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "rai@email.com",
  "password": "12345678"
}

###

# @name create_task
POST {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "content": "Finalizar a aplicação",
  "checked": false
}

###

# @name get_task
GET {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

###

# @name change_checked_task
PATCH {{baseUrl}}/tasks/db83a010-0071-4bac-9080-a78e133d4046
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

###

# @name delete_task
DELETE {{baseUrl}}/tasks/db83a010-0071-4bac-9080-a78e133d4046
Content-Type: application/json
Authorization: Bearer {{AuthToken}}
